import express, { type Response } from 'express'; import mongoose from 'mongoose'; import cors from 'cors'; import helmet from 'helmet'; import rateLimit from 'express-rate-limit'; import argon2 from 'argon2'; import multer from 'multer'; import { z } from 'zod'; import { env } from './config.js'; import { requireAuth, signToken, type AuthedRequest } from './auth.js'; import { Document, Listing, Match, Profile, User } from './models.js'; import { decrypt, encryptAndStore, removeObject } from './crypto-storage.js';

const app = express(); app.use(helmet()); app.use(cors({ origin: env.FRONTEND_URL, methods: ['GET', 'POST', 'PATCH', 'DELETE'], allowedHeaders: ['Content-Type', 'Authorization'] })); app.use(express.json({ limit: '100kb' })); app.use('/api/auth', rateLimit({ windowMs: 15 * 60_000, limit: 10, standardHeaders: true }));
const asyncRoute = (fn: (req: AuthedRequest, res: Response) => Promise<unknown>) => (req: AuthedRequest, res: Response) => void fn(req, res).catch((e: unknown) => { if (e instanceof z.ZodError) return res.status(400).json({ error: 'Ungültige Eingabe.', details: e.flatten() }); console.error(e); res.status(500).json({ error: 'Interner Fehler.' }); });
const registerSchema = z.object({ name: z.string().min(2).max(80), email: z.string().email(), password: z.string().min(12).max(128) });
const profileBaseSchema = z.object({ name: z.string().min(1).max(80), locations: z.array(z.object({ city: z.string().min(1), districts: z.array(z.string()).default([]) })).min(1), radiusKm: z.number().min(0).max(200).default(5), rent: z.object({ coldMin: z.number().nonnegative().optional(), coldMax: z.number().nonnegative().optional(), warmMin: z.number().nonnegative().optional(), warmMax: z.number().nonnegative().optional() }).default({}), rooms: z.object({ min: z.number().positive().optional(), max: z.number().positive().optional() }).default({}), area: z.object({ min: z.number().positive().optional(), max: z.number().positive().optional() }).default({}), propertyTypes: z.array(z.enum(['wg', 'apartment', 'house'])).default([]), features: z.array(z.string().max(40)).default([]), availableFrom: z.coerce.date().optional(), documentIds: z.array(z.string()).default([]), active: z.boolean().default(true) });
const profileSchema = profileBaseSchema.refine((x) => !x.rent.coldMin || !x.rent.coldMax || x.rent.coldMin <= x.rent.coldMax, { message: 'Ungültiger Mietbereich.' });

app.post('/api/auth/register', asyncRoute(async (req, res) => { const data = registerSchema.parse(req.body); if (await User.exists({ email: data.email.toLowerCase() })) return res.status(409).json({ error: 'E-Mail-Adresse ist bereits registriert.' }); const user = await User.create({ name: data.name, email: data.email, passwordHash: await argon2.hash(data.password, { type: argon2.argon2id }) }); res.status(201).json({ token: signToken(String(user._id)), user: { id: user.id, name: user.name, email: user.email } }); }));
app.post('/api/auth/login', asyncRoute(async (req, res) => { const data = z.object({ email: z.string().email(), password: z.string().min(1) }).parse(req.body); const user = await User.findOne({ email: data.email.toLowerCase() }); if (!user || !(await argon2.verify(user.passwordHash, data.password))) return res.status(401).json({ error: 'E-Mail oder Passwort ist falsch.' }); res.json({ token: signToken(user.id), user: { id: user.id, name: user.name, email: user.email } }); }));
app.get('/api/auth/me', requireAuth, asyncRoute(async (req, res) => { const user = await User.findById(req.userId).select('name email notificationPreferences'); res.json({ user }); }));

app.get('/api/profiles', requireAuth, asyncRoute(async (req, res) => res.json({ profiles: await Profile.find({ userId: req.userId }).sort({ createdAt: -1 }) })));
app.post('/api/profiles', requireAuth, asyncRoute(async (req, res) => { const data = profileSchema.parse(req.body); const docIds = data.documentIds.map((id) => new mongoose.Types.ObjectId(id)); if (docIds.length && await Document.countDocuments({ _id: { $in: docIds }, userId: req.userId }) !== docIds.length) return res.status(400).json({ error: 'Ungültiges Dokument gewählt.' }); const profile = await Profile.create({ ...data, documentIds: docIds, userId: req.userId }); await Document.updateMany({ _id: { $in: docIds } }, { $addToSet: { profileIds: profile._id } }); res.status(201).json({ profile }); }));
app.get('/api/profiles/:id', requireAuth, asyncRoute(async (req, res) => { const profile = await Profile.findOne({ _id: req.params.id, userId: req.userId }); if (!profile) return res.status(404).json({ error: 'Profil nicht gefunden.' }); res.json({ profile }); }));
app.patch('/api/profiles/:id', requireAuth, asyncRoute(async (req, res) => { const data = profileBaseSchema.partial().parse(req.body); const profile = await Profile.findOneAndUpdate({ _id: req.params.id, userId: req.userId }, data, { new: true, runValidators: true }); if (!profile) return res.status(404).json({ error: 'Profil nicht gefunden.' }); res.json({ profile }); }));
app.delete('/api/profiles/:id', requireAuth, asyncRoute(async (req, res) => { const removed = await Profile.findOneAndDelete({ _id: req.params.id, userId: req.userId }); if (!removed) return res.status(404).json({ error: 'Profil nicht gefunden.' }); await Document.updateMany({ profileIds: removed._id }, { $pull: { profileIds: removed._id } }); res.status(204).end(); }));

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024, files: 1 }, fileFilter: (_req, file, cb) => cb(null, ['application/pdf', 'image/jpeg', 'image/png'].includes(file.mimetype)) });
function hasExpectedSignature(file: Express.Multer.File) { const b = file.buffer; return (file.mimetype === 'application/pdf' && b.subarray(0, 5).toString() === '%PDF-') || (file.mimetype === 'image/jpeg' && b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff) || (file.mimetype === 'image/png' && b.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))); }
app.get('/api/documents', requireAuth, asyncRoute(async (req, res) => res.json({ documents: await Document.find({ userId: req.userId }).select('-encryptedDek -iv -authTag -objectKey').sort({ createdAt: -1 }) })));
app.post('/api/documents', requireAuth, upload.single('file'), asyncRoute(async (req, res) => { if (!req.file || !hasExpectedSignature(req.file)) return res.status(400).json({ error: 'PDF, JPEG oder PNG bis 10 MB erforderlich.' }); const kind = z.enum(['income', 'credit_report', 'identity', 'self_disclosure', 'other']).parse(req.body.kind); const stored = await encryptAndStore(req.userId!, req.file.buffer, req.file.mimetype); const document = await Document.create({ ...stored, userId: req.userId, kind, originalName: req.file.originalname.replace(/[^\w. -]/g, '_') }); res.status(201).json({ document: { id: document.id, kind: document.kind, originalName: document.originalName, mimeType: document.mimeType, size: document.size, status: document.status, createdAt: document.createdAt } }); }));
app.get('/api/documents/:id', requireAuth, asyncRoute(async (req, res) => { const document = await Document.findOne({ _id: req.params.id, userId: req.userId }); if (!document) return res.status(404).json({ error: 'Dokument nicht gefunden.' }); if (document.status !== 'clean') return res.status(423).json({ error: 'Dokument ist noch nicht für den Abruf freigegeben.' }); const body = await decrypt(document); res.setHeader('Content-Type', document.mimeType); res.setHeader('Content-Disposition', `attachment; filename="${document.originalName}"`); res.send(body); }));
app.delete('/api/documents/:id', requireAuth, asyncRoute(async (req, res) => { const document = await Document.findOneAndDelete({ _id: req.params.id, userId: req.userId }); if (!document) return res.status(404).json({ error: 'Dokument nicht gefunden.' }); await removeObject(document.objectKey); await Profile.updateMany({ documentIds: document._id }, { $pull: { documentIds: document._id } }); res.status(204).end(); }));

app.get('/api/matches', requireAuth, asyncRoute(async (req, res) => { const filter: Record<string, unknown> = { userId: req.userId }; if (typeof req.query.profileId === 'string') filter.profileId = req.query.profileId; if (typeof req.query.status === 'string') filter.status = req.query.status; const matches = await Match.find(filter).populate('listingId').populate('profileId', 'name').sort({ createdAt: -1 }); res.json({ matches }); }));
app.patch('/api/matches/:id', requireAuth, asyncRoute(async (req, res) => { const status = z.enum(['new', 'saved', 'dismissed', 'applied']).parse(req.body.status); const match = await Match.findOneAndUpdate({ _id: req.params.id, userId: req.userId }, { status }, { new: true }); if (!match) return res.status(404).json({ error: 'Treffer nicht gefunden.' }); res.json({ match }); }));
app.get('/api/listings/:id', requireAuth, asyncRoute(async (req, res) => { const match = await Match.findOne({ userId: req.userId, listingId: req.params.id }).populate('listingId'); if (!match) return res.status(404).json({ error: 'Inserat nicht gefunden.' }); res.json({ listing: match.listingId }); }));

app.use((err: unknown, _req: express.Request, res: Response, _next: express.NextFunction) => { if (err instanceof z.ZodError) return res.status(400).json({ error: 'Ungültige Eingabe.', details: err.flatten() }); if (err instanceof multer.MulterError) return res.status(400).json({ error: err.message }); console.error(err); res.status(500).json({ error: 'Interner Fehler.' }); });
mongoose.connect(env.MONGODB_URI).then(() => app.listen(env.PORT, () => console.log(`API läuft auf :${env.PORT}`))).catch((err) => { console.error('MongoDB-Verbindung fehlgeschlagen', err); process.exit(1); });
